# Generated by Django 2.0.6 on 2018-07-15 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_guid', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date file uploaded')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='date last modified')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('user_guid', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('cellphone', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('account_type', models.CharField(max_length=256)),
                ('date_registration', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date account created')),
                ('date_last_login', models.DateTimeField(auto_now=True, verbose_name='date last logined')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
