# Generated by Django 2.0.6 on 2018-08-15 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_guid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('total_page', models.PositiveIntegerField(default=1)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date file uploaded')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='date last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_guid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date account created')),
                ('group_name', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
                ('shared_file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.File')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_guid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.PositiveIntegerField()),
                ('top', models.IntegerField(default=-1)),
                ('bot', models.IntegerField(default=-1)),
                ('left', models.IntegerField(default=-1)),
                ('right', models.IntegerField(default=-1)),
                ('status', models.CharField(default='', max_length=256)),
                ('page', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('share_guid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_guid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('cellphone', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('account_type', models.CharField(max_length=256)),
                ('date_registration', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date account created')),
                ('date_last_login', models.DateTimeField(auto_now=True, verbose_name='date last logined')),
            ],
        ),
        migrations.AddField(
            model_name='share',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='share_owner', to='user.User'),
        ),
        migrations.AddField(
            model_name='share',
            name='share_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='share_user', to='user.User'),
        ),
        migrations.AddField(
            model_name='share',
            name='shared_file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.File'),
        ),
        migrations.AddField(
            model_name='object',
            name='editor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='object',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.File'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='shared_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
