# Generated by Django 2.0.6 on 2018-07-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.PositiveIntegerField(),
        ),
    ]
