# Generated by Django 2.0.6 on 2018-07-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoty', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='co_editor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='file',
            name='groups',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='co_edit_files',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='object',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.File'),
        ),
    ]
