# Generated by Django 2.0.6 on 2018-07-09 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fule_guid', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('date_uploaded', models.DateTimeField(verbose_name='date file uploaded')),
                ('pub_last_modified', models.DateTimeField(verbose_name='date last modified')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
