# Generated by Django 2.0.6 on 2018-07-09 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180709_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='date last logined'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date account created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date file uploaded'),
        ),
        migrations.AlterField(
            model_name='file',
            name='pub_last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date last modified'),
        ),
    ]
