# Generated by Django 2.0.6 on 2018-07-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180726_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='totoal_page',
            new_name='total_page',
        ),
    ]
