# Generated by Django 2.0.6 on 2018-09-11 02:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification_code',
            fields=[
                ('verification_code', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(editable=False, max_length=256)),
                ('date_requested', models.DateTimeField(default=None, verbose_name='date file uploaded')),
                ('date_expired', models.DateTimeField(default=None, verbose_name='date file uploaded')),
                ('date_activated', models.DateTimeField(default=None, verbose_name='date file uploaded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
