# Generated by Django 2.0.6 on 2018-07-23 01:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180719_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='', max_length=256)),
                ('date_registration', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date account created')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_guid', models.CharField(default='', max_length=256)),
                ('user_guid', models.CharField(default='', max_length=256)),
                ('permission', models.CharField(default='', max_length=256)),
                ('operator_guid', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_guid', models.CharField(default='', max_length=256)),
                ('group_id', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='object',
            old_name='categoty',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='content',
            new_name='coordinate',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='file',
            new_name='file_id',
        ),
        migrations.AddField(
            model_name='object',
            name='editor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='object',
            name='status',
            field=models.CharField(default='', max_length=256),
        ),
    ]
