# Generated by Django 2.0.6 on 2018-08-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180726_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='object',
            name='bot',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='object',
            name='left',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='object',
            name='right',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='object',
            name='top',
            field=models.IntegerField(default=-1),
        ),
    ]
