# Generated by Django 2.0.6 on 2018-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180808_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filegroup',
            old_name='File',
            new_name='file',
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
