# Generated by Django 2.0.6 on 2018-07-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180723_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='operator_guid',
            new_name='owner_guid',
        ),
    ]
