# Generated by Django 2.0.6 on 2018-08-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180813_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='GroupMember',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='group',
            new_name='share_group',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='user',
            new_name='shared_user',
        ),
    ]
