# Generated by Django 2.0.6 on 2018-07-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180723_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='file_guid',
        ),
        migrations.RemoveField(
            model_name='share',
            name='owner_guid',
        ),
        migrations.RemoveField(
            model_name='share',
            name='user_guid',
        ),
        migrations.AddField(
            model_name='share',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.File'),
        ),
        migrations.AddField(
            model_name='share',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='share',
            name='share_user',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
