# Generated by Django 2.0.6 on 2018-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180911_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification_code',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
