# Generated by Django 2.0.6 on 2018-08-15 05:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180814_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
                ('shared_file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.File')),
            ],
        ),
        migrations.RemoveField(
            model_name='filegroup',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filegroup',
            name='group',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='share_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Group'),
        ),
        migrations.DeleteModel(
            name='FileGroup',
        ),
    ]
