# Generated by Django 2.0.6 on 2018-07-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180723_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='file',
            new_name='file_guid',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='share_user',
            new_name='share_user_guid',
        ),
    ]
