# Generated by Django 2.0.6 on 2018-07-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180723_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='file_guid',
            new_name='file',
        ),
    ]
