# Generated by Django 2.0.6 on 2018-08-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180815_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='share_group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='shared_user',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
