# Generated by Django 2.0.6 on 2018-08-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180815_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
                ('shared_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
