# Generated by Django 2.0.6 on 2018-08-15 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_groupmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='id',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group_member_guid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
