# Generated by Django 2.0.6 on 2018-08-15 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180815_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group_member_guid',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
